### ISSUE TITLE
tap interface names are truncated.

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/hil-vpn#14]
The openvpn config files we're generating have a significant prefix in the names for the tap devices that is the same:

https://github.com/zenhack/hil-vpn/blob/dba0ec73aa385451c576e95cb84a46ecbed08251/cmd/hil-vpn-privop/openvpn-conf.go#L16

The daemon adds some prefixing of its own, and apparently there is a relatively small cap on the length of interface names on linux. The upshot of all this is that all of the configs end up creating an interface called `tap-hil-vpn-hil`, so we can't actually start more than one vpn at a time without getting an in-use error.

We need to re-work the way we generate device names to avoid this.

**Comment by zenhack** [comment]
One thing we could do is just make the device name a hash of the stuff we're feeding it now, maybe base64-encoded. Even truncated, that should give us enough entropy to be a non-issue.

**Comment by naved001** [comment]
what if we shorten the prefix to `tapHV-` that will give us 9 characters to encode useful information in the name? The hash is fine too, honestly. Let's implement whatever is straightforward.

**Comment by ianballou** [comment]
I think the hash sounds like a good idea, seems pretty straight forward.

**Comment by zenhack** [comment]
@naved001, I actually did more-or-less that in my pr #15. I think it's a little better than a hash in that the caller has less control over it, but per the comments I don't think it's that big of a deal.
